### ISSUE TITLE
config.yml

### ISSUE THREAD

**Issue by markbeep** [markbeep/Tez#1]
Use a yaml file for configuring keybinds. Exact syntax can vary. At first simply reading the function name should suffice. Later points reading the amount of times to complete a function could be relevant and a step afterwards would be to execute multiple functions.

- [ ] Read basic functions in a config file
- [ ] Read iterations. Either as a second yaml argument (i.e. `times: 0`) or as the function argument.
- [ ] Execute multiple functions. Have to look in detail what the best way to execute this would be.

Example:
```yaml
keybinds:
  c-s:
    func: saveFile
  c-d: # go down by 10 lines
    func: moveDown(10)
  c-w: # multiple functions
    func: |
      discardChanges()
      moveToLine(0)
      closeFile()
```
